### ISSUE TITLE
the contextCursor is not included in repo

### ISSUE THREAD

**Issue by vinstah** [AndrewKuktenko/kandy.app#2]
Hi,

very happy to find this new project with interesting ideas, I cloned the repo and couldn't run because the file src/libs/context-cursor/contextCursor does not exist, I think it is set up as a symlink

one question is there a way to speed up the cursor it feels lagging behind the original mouse cursor

**Comment by AndrewKuktenko** [comment]
Hey @vinstah,

Yes, I cloned this lib [https://github.com/PavelLaptev/context-cursor](https://github.com/PavelLaptev/context-cursor) to be able to add such a cursor as it is not available in npm. 
Maybe I should update my readme file. 
I am sure this cursor could be improved in some way.
